config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'search', to: "homes#search"
  get 'category', to: "homes#category"
  get 'index', to: "homes#index"

  resources :persons do
    resources :donations do
      resources :questions do
        resources :answers
      end
      member do
        put 'image', to: "donations#delete_image"
      end
    end
  end

  root 'homes#index'

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :person
  belongs_to :donation
  has_one :answer, dependent: :destroy

  validates :question, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :find_question, only: [:edit, :update, :destroy]
  before_action :find_user
  before_action :find_donation, only: [:create, :edit, :update, :destroy]
  before_action :authenticate_user!

  def create
    @question = @donation.questions.create(question_params)
    @question.person = @person
    if @question.save
      redirect_to person_donation_path(@person, @donation), notice: "Question Created"
    else
      @categories = Category.all
      redirect_to :back
    end
  end

  def edit
    if current_user.id != @question.person.id
      redirect_to 'https://quem-me-quer.herokuapp.com/'
    else
       @question
    end
  end

  def update
    if @question.update(question_params)
      redirect_to person_donation_path(@person, @donation), notice: "Question Updated"
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to person_donation_path(@person, @donation), notice: "Question Deleted"
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:question)
  end

  def find_donation
    @donation = Donation.find(params[:donation_id])
  end

  def find_user
    @person = Person.find(current_user.id) if current_user != nil
  end
end

app/views/questions/_form.html.erb
<% if current_user %>
  <%= form_for([@person, @donation, @donation.questions.build], validate: true) do |f| %>
    <div class="row">
      <div class="form-group col-md-12">
        <%= f.label :question %>
        <%= f.text_area :question, rows: 5, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-12">
        <%= f.submit "Save", class: "btn btn-primary form-control" %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="row">
    <div class="form-group col-md-12">
      <p><%= link_to "Log in", user_session_path %> to make a question</p>
    </div>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p><%= question.question %></p>
        <p><small>Posted by <%= question.person.user.email %> <%= time_ago_in_words(question.created_at) %> ago</small></p>
        <% if question.answer %>
          <div class="panel-body">
            <p><%= question.answer.answer %></p>
            <p><small>Answered <%= time_ago_in_words(question.answer.created_at) %> ago</small></p>
          </div>
        <% end %>
      </div>
      <% if current_user %>
        <div class="panel-body">
          <% if current_user.id == @donation.person.id && question.answer %>
            <%= link_to "Edit", edit_person_donation_question_answer_path(@person, @donation, question, question.answer) %>
            <%= link_to "Delete", person_donation_question_answer_path(@person, @donation, question, question.answer), method: :delete, data: { confirm: "Delete?" } %>
          <% end %>
          <% if current_user.id == question.person.id %>
            <%= link_to "Edit", edit_person_donation_question_path(@person, @donation, question) %>
            <%= link_to "Delete", person_donation_question_path(@person, @donation, question), method: :delete, data: { confirm: 'Delete?' } %>
          <% end %>
          <% if current_user.id == @donation.person.id && question.answer == nil %>
            <%= link_to "Answer", new_person_donation_question_answer_path(@person, @donation, question) %>
          <% end %>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <% if @question.errors.any? %>
      <div class="alert alert-danger">
        <% @question.errors.full_messages.each do |e| %>
          <p><%= e %></p>
        <% end %>
      </div>
    <% end %>
    <%= form_for ([@person, @donation, @question]) do |f| %>
      <div class="form-group">
        <%= f.label :question %>
        <%= f.text_area :question, rows:5, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-primary form-control" %>
      </div>
    <% end %>
  </div>
</div>