config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'search', to: "homes#search"
  get 'category', to: "homes#category"
  get 'index', to: "homes#index"

  resources :persons do
    resources :donations do
      resources :questions do
        resources :answers
      end
      member do
        put 'image', to: "donations#delete_image"
      end
    end
  end

  root 'homes#index'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :person
  has_many :photos, dependent: :destroy
  belongs_to :category
  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :title, :description, :situation, :category, presence: true
  validates :title, length: { maximum: 60 }

  has_many :questions, dependent: :destroy
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  before_action :find_user
  before_action :find_categories, only: [:new, :edit, :delete_image]
  before_action :find_donation, only: [:show, :edit, :update, :destroy, :delete_image]
  before_action :authenticate_user!, except: [:show]

  def index
    @donations = @person.donations.includes(:photos).all.paginate(:page => params[:page], :per_page => 3)
  end

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    @donation.person_id = @person.id
    @donation.category_id = params[:donation][:category_id]
    if @donation.status == '1' && params[:images] == nil
      @categories = Category.all
      flash[:alert] = 'Para publicar uma doação é necessário anexar pelo menos 1 foto'
      return render 'new'
    end
    if params[:images]
      params[:images].each { |image| @donation.photos.new(image: image) }
    end
    if @donation.save
      redirect_to person_donation_path(@person, @donation), notice: "Donation created"
    else
      @categories = Category.all
      render 'new'
    end
  end

  def show

  end

  def edit
    if current_user.id != @donation.person.id
      redirect_to 'https://quem-me-quer.herokuapp.com/'
    else
      @categories = Category.all
      @donation
    end
  end

  def update
    @donation.attributes = donation_params
    if params[:images] == nil
      if @donation.status == '1' && (@donation.photos.count == 0)
        @categories = Category.all
        flash[:alert] = 'Para publicar uma doação é necessário anexar pelo menos 1 foto'
        return render 'edit'
      else
        if @donation.save
          return redirect_to person_donation_path(@person, @donation), notice: "Donation updated"
        else
          @categories = Category.all
          return render 'edit'
        end
      end
    else
      if @donation.update(donation_params)
        if params[:images]
          params[:images].each { |image| @donation.photos.create(image: image) }
        end
        return redirect_to person_donation_path(@person, @donation), notice: "Donation updated"
      else
        @categories = Category.all
        return render 'edit'
      end
    end

  end

  def destroy
    @donation.destroy
    redirect_to person_donations_path, notice: "Donation deleted"
  end

  def delete_image
    if @donation.photos.count == 1 && @donation.status == '1'
      flash[:alert] = "Não pode deletar todas as fotos se a doação estiver publicada"
      return render 'edit'
    end
    photo = Photo.find(params[:format])
    flash[:notice] = "Image deleted"
    photo.destroy
    render 'edit'
  end

  private

  def donation_params
    params.require(:donation).permit(:category_id, :title, :description, :status, :situation, :images, :question)
  end

  def find_donation
    @donation = Donation.find(params[:id])
  end

  def find_categories
    @categories = Category.all
  end

  def find_user
    @person = Person.find(current_user.id) if current_user != nil
  end

end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for([@person, @donation], html: { multipart: true }, validate: true)  do |f| %>
  <div class="row">
    <div class="col-md-12">
      <% if @donation.errors.any? %>
        <div class="alert alert-danger">
          <% @donation.errors.full_messages.each do |e| %>
            <p><%= e %></p>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="form-group col-md-12">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-12">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-12">
      <%= f.radio_button :situation, 'Semi-Novo', checked: true %>
      <%= label_tag 'donation_situation_semi-novo', 'Semi-Novo' %>
      <%= f.radio_button :situation, 'Usado' %>
      <%= label_tag 'donation_situation_usado', 'Usado' %>
      <%= f.radio_button :situation, 'Quebrado' %>
      <%= label_tag 'donation_situation_quebrado', 'Quebrado' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-12">
      <!-- Procurar outro jeito de usar o label com radio button -->
      <% i = 1 %>
      <% @categories.each do |category| %>
        <% if i == 1 %>
          <%= f.radio_button :category_id, category.id, checked: true %>
        <% else %>
          <%= f.radio_button :category_id, category.id %>
        <% end %>
        <%= label_tag 'donation_category_id_'+i.to_s, category.name %>
        <% i = i + 1 %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <% (@donation.photos.size..5).each do %>
        <%= file_field_tag "images[]", type: :file, multiple: true %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="form-group">
      <% if @donation.photos %>
        <% @donation.photos.each do |photo| %>
          <div class="col-xs-12 col-sm-6 col-md-4 delete">
            <%= link_to (image_tag(photo.image_url(:thumbnail), class:"img-responsive")), photo.image.url %>
            <div class="delete_icon" style="position: relative; top: -195px; left: 135px; opacity: 1;">
              <%= link_to image_person_donation_path(@person, @donation, photo), method: :put, data: { confirm: "delete?" } do %>
                <p class="btn btn-danger">Delete <span class="glyphicon glyphicon-trash"></p>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function(){
      $(".delete_icon").hide();
      $(".delete").hover(function(){
        $(this).css("opacity", "0.5");
        $(".delete_icon").toggle();
      }, function(){
        $(this).css("opacity", "1");
        $(".delete_icon").toggle();
      });
    })
  </script>

  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :status, "Publish" %>
      <%= f.check_box :status %>
    </div>

  </div>

  <div class="row">
    <div class="form-group col-md-12">
      <%= f.submit "Save", class: "btn btn-primary form-control" %>
    </div>
  </div>

<% end %>

app/views/donations/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/donations/index.html.erb
<h1>index</h1>
<% @donations.each do |donation| %>
  <div class="row">
      <div class="col-sm-3 col-xs-6">
        <% if donation.photos.any? %>
          <%= link_to link_to (image_tag(donation.photos[0].image_url(:thumbnail), class:"img-responsive thumbnail")), person_donation_path(@person,donation) %>
        <% end %>
      </div>
      <div class="col-sm-7 col-xs-6">
        <h1><%= donation.title %></h1>
        <p><%= truncate(donation.description, length: 200) %></p>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="row">
          <%= link_to "Edit", edit_person_donation_path(@person, donation), class: "btn btn-sm btn-default col-xs-6 col-sm-7" %>
          <%= link_to "Delete", [@person, donation], method: :delete, data: { confirm: "Delete?" }, class: "btn btn-sm btn-default col-xs-6 col-sm-7" %>
        </div>
      </div>
    </div>
  <br>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @donations, :container => false %>
  <div class="page_info">
    <%= page_entries_info @donations %>
  </div>
</div>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form' %>

app/views/donations/show.html.erb
<div class="row">
  <div class="form-group col-md-12">
    <h1><%= @donation.title %></h1>
    <p><%= @donation.description %></p>
    <p><%= @donation.situation %></P>
  </div>
</div>

<div class="row">
  <div class="form-group">
    <% if @donation.photos %>
      <% @donation.photos.each do |photo| %>
        <div class="col-sm-6 col-md-4 thumbnail">
          <%= link_to (image_tag(photo.image_url(:standard), class:"img-responsive")), photo.image.url %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= render @donation.questions %>

<%= render 'questions/form' %>