config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'search', to: "homes#search"
  get 'category', to: "homes#category"
  get 'index', to: "homes#index"

  resources :persons do
    resources :donations do
      resources :questions do
        resources :answers
      end
      member do
        put 'image', to: "donations#delete_image"
      end
    end
  end

  root 'homes#index'

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  before_action :find_user
  before_action :find_categories, only: [:search, :category]

  def index
    @donations1 = Donation.includes(:photos).all.order("created_at DESC").where(status: 1, category_id: 1).limit(8)
    @donations2 = Donation.includes(:photos).all.order("created_at DESC").where(status: 1, category_id: 2).limit(8)
    @donations3 = Donation.includes(:photos).all.order("created_at DESC").where(status: 1, category_id: 3).limit(8)

    @donations = Array.new
    @donations << @donations1
    @donations << @donations2
    @donations << @donations3

    respond_to do |format|
      format.html { @donations }
      format.json { render json: @donations }
    end
  end

  def search
    @donations = Donation.includes(:photos).where(status: 1).where("title like ? or description like ?", "%#{params[:search]}%", "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 3)
  end

  def category
    if params[:category] == nil
      @donations = Donation.includes(:photos).where(status: 1).where("title like ? or description like ?", "%#{params[:title]}%", "%#{params[:title]}%").paginate(:page => params[:page], :per_page => 3)
    else
      @donations = Donation.includes(:photos).where(status: 1).where("category_id = ?", "#{params[:category][:category_id]}").where("title like ? or description like ?", "%#{params[:title]}%", "%#{params[:title]}%").paginate(:page => params[:page], :per_page => 3)
    end
    render 'search'
  end

  private

  def find_user
    @person = Person.find(current_user.id) if current_user != nil
  end

  def find_categories
    @categories = Category.all
  end
end

app/views/homes/index.html.erb
<h1>Welcome</h1>

<div class="row">
  <% @donations.each do |donations| %>
    <h3 class="text-center"><%= donations[0].category.name %></h3>
    <div class="owl-carousel">
      <% donations.each do |donation| %>
        <% if donation.photos.any? %>
          <div class="col-xs-12 col-sm-12 col-md-offset-1 col-md-10 thumbnail">
            <%= link_to (image_tag(donation.photos[0].image_url(:index_page, :crop=>:scale), class:"img-responsive")), person_donation_path(donation.person,donation) %>
          </div>
        <% else %>
          <div class="col-xs-12 col-sm-12 col-md-offset-1 col-md-10 thumbnail">
            <%= link_to donation.title, person_donation_path(donation.person,donation), class:"img-responsive" %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="row" style=margin-top:50px>
  <div style="padding-top:15px">
    <div class="col-sm-1 col-sm-offset-4 col-xs-3" >
      <%= link_to cl_image_tag("Facebook_logo-2_g86xl9.png", :width=>40, :crop=>:scale), "#" %>
    </div>
    <div class="col-sm-1 col-xs-3">
      <%= link_to cl_image_tag("Twitter_logo-5_i7dtqx.png", :width=>40, :crop=>:scale), "#" %>
    </div>
    <div class="col-sm-1 col-xs-3">
      <%= link_to cl_image_tag("Googleplus_t554ie.png", :width=>40, :crop=>:scale), "#" %>
    </div>
    <div class="col-sm-1 col-xs-3">
      <%= link_to cl_image_tag("20130729004843_Youtube_logo_rkrib5.png", :width=>40, :height=>40, :crop=>:scale), "#" %>
    </div>
  </div>
</div>

<script>
  $(".owl-carousel").owlCarousel({
    navigation : true, // Show next and prev buttons
    autoPlay : 6000,
    stopOnHover : true,
    slideSpeed : 400,
    paginationSpeed : 600,
    singleItem:true
  });
</script>

app/views/homes/search.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1 class="form-group">Search</h1>
  </div>

  <div class="col-sm-3">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#search-options" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        Buscar <span class="glyphicon glyphicon-search"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="search-options">
      <%= form_for :category, url: category_path, method: :get do |f| %>
        <% i = 1 %>
        <% @categories.each do |category| %>
          <div class="row">
            <div class="col-sm-12">
              <%= f.radio_button :category_id, category.id %>
              <%= label_tag 'category_category_id_'+i.to_s, category.name %>
            </div>
          </div>
          <% i = i + 1 %>
        <% end %>
        <div class="row">
          <div class="col-sm-12 form-group">
            <%= text_field_tag(:title, nil, class: "form-control", placeholder: "title/description") %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 form-group">
            <%= f.submit "Search", class: "btn btn-default form-control" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-sm-9">
    <% @donations.each do |donation| %>
      <div class="row">
          <div class="col-sm-4">
            <% if donation.photos.any? %>
              <%= link_to link_to (image_tag(donation.photos[0].image_url(:thumbnail), class:"img-responsive thumbnail")), person_donation_path(donation.person,donation) %>
            <% end %>
          </div>
          <div class="col-sm-8">
            <h1><%= donation.title %></h1>
            <p><%= truncate(donation.description, length: 200) %></p>
          </div>
        </div>
      <br>
    <% end %>
  </div>
</div>

<div class="flickr_pagination">
  <%= will_paginate @donations, :container => false %>
  <div class="page_info">
    <%= page_entries_info @donations %>
  </div>
</div>