config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'search', to: "homes#search"
  get 'category', to: "homes#category"
  get 'index', to: "homes#index"

  resources :persons do
    resources :donations do
      resources :questions do
        resources :answers
      end
      member do
        put 'image', to: "donations#delete_image"
      end
    end
  end

  root 'homes#index'

end

app/views/layouts/_alert.html.erb
<div class="alert
    <%=
    case type.to_sym
    when :alert, :danger, :error, :validation_errors
        'alert-danger'
    when :warning, :todo
        'alert-warning'
    when :notice, :success
        'alert-success'
    else
        'alert-info'
    end
    %>
     alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= content %>
</div>

app/views/layouts/_footer.html.erb
<div class="navbar-inverse" style="margin-top:100px">
  <div class="container">
    <ul class="nav navbar-nav col-sm-6 col-xs-6">
      <li><%= link_to "Home", "#" %><li>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Termos e Condições", "#" %><li>
      <li><%= link_to "Política de Privacidade", "#" %></li>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sign" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#search-header" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-search" style="color:white"></span>
      </button>

      <% if signed_in? %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#user-info" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="glyphicon glyphicon-user" style="color:white"></span>
        </button>
      <% end %>
      <a class="navbar-brand" href="/"><%= t('.brand') %></a>
    </div>

    <ul class="nav navbar-nav collapse navbar-collapse" id="search-header">
      <li>
        <%= form_tag(search_path, class: "navbar-form", role: "search", method: :get) do %>
          <div class="form-group">
            <%= text_field_tag :search, nil, class: "form-control", placeholder: "Search" %>
          </div>
          <button type="submit" class="btn btn-default form-control">Submit</button>
        <% end %>
      </li>
    </ul>

    <% if signed_in? %>
      <ul class="nav navbar-nav collapse navbar-collapse" id="user-info">
        <li><%= link_to t(".edit"), edit_person_path(@person) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t(".donation") %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t(".new_donation"), new_person_donation_path(@person) %></li>
            <li><%= link_to t(".list_donation"), person_donations_path(@person) %></li>
          </ul>
        </li>
      </ul>
    <% end %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="sign">
      <ul class="nav navbar-nav navbar-right">
        <% if !signed_in? %>
          <li><%= link_to t(".sign_up"), new_user_registration_path %></li>
          <li><%= link_to t(".sign_in"), new_user_session_path %></li>
        <% else %>
          <li><%= link_to t(".account"), edit_user_registration_path %></li>
          <li><%= link_to t(".sign_out"), destroy_user_session_path, method: :delete %></li>
        <% end %>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t(".language") %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "EN", locale: "en" %></li>
            <li><%= link_to "PT", locale: "pt-BR" %></li>
          </ul>
        </li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<script>
  $('.navbar').on('show.bs.collapse', function () {
      var actives = $(this).find('.collapse.in'),
          hasData;

      if (actives && actives.length) {
          hasData = actives.data('collapse')
          if (hasData && hasData.transitioning) return
          actives.collapse('hide')
          hasData || actives.data('collapse', null)
      }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="rKgTjM7SgxaOx4pSDsFk7fb1c2ctN3o6SOdl9kPHAn0" />
  <title><%= content_for?(:title) ? yield(:title) : "Quem Me Quer" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Quem Me Quer" %>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render '/layouts/header' %>
  </header>

  <div class="container">
    <% flash.each do |type, content| %>
      <% if content.respond_to?('each') %>
        <% content.each do |item| %>
          <%= render 'layouts/alert', type: type, content: item %>
        <% end %>
      <% else %>
        <%= render 'layouts/alert', type: type, content: content %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>

  <footer>
    <%= render '/layouts/footer' %>
  </footer>
</body>
</html>